/// Flutter icons AtmosphereIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AtmosphereIcon
///      fonts:
///       - asset: fonts/AtmosphereIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AtmosphereIcon {
  AtmosphereIcon._();

  static const _kFontFam = 'AtmosphereIcon';
  static const _kFontPkg = null;

  static const IconData airballoon_outline = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
