/// Flutter icons CalendarIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CalendarIcon
///      fonts:
///       - asset: fonts/CalendarIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CalendarIcon {
  CalendarIcon._();

  static const _kFontFam = 'CalendarIcon';
  static const String _kFontPkg = null;

  static const IconData calendar_month_outline = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
