/// Flutter icons ExpandIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ExpandIcon
///      fonts:
///       - asset: fonts/ExpandIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ExpandCustomIcon {
  ExpandCustomIcon._();

  static const _kFontFam = 'ExpandIcon';
  static const _kFontPkg = null;

  static const IconData arrow_expand = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
