/// Flutter icons IssIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IssIcon
///      fonts:
///       - asset: fonts/IssIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IssIcon {
  IssIcon._();

  static const _kFontFam = 'IssIcon';
  static const String _kFontPkg = null;

  static const IconData satellite = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
