/// Flutter icons OrbitIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OrbitIcon
///      fonts:
///       - asset: fonts/OrbitIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class OrbitIcon {
  OrbitIcon._();

  static const _kFontFam = 'OrbitIcon';
  static const _kFontPkg = null;

  static const IconData orbit = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
