/// Flutter icons RocketIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RocketIcon
///      fonts:
///       - asset: fonts/RocketIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class RocketIcon {
  RocketIcon._();

  static const _kFontFam = 'RocketIcon';
  static const _kFontPkg = null;

  static const IconData rocket_outline = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
