/// Flutter icons TelescopeIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TelescopeIcon
///      fonts:
///       - asset: fonts/TelescopeIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class TelescopeIcon {
  TelescopeIcon._();

  static const _kFontFam = 'TelescopeIcon';
  static const String? _kFontPkg = null;

  static const IconData telescope =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
