/// Flutter icons UpcomingIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  UpcomingIcon
///      fonts:
///       - asset: fonts/UpcomingIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class UpcomingIcon {
  UpcomingIcon._();

  static const _kFontFam = 'UpcomingIcon';
  static const _kFontPkg = null;

  static const IconData page_next_outline = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
