/// Flutter icons Youtube
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Youtube
///      fonts:
///       - asset: fonts/Youtube.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Youtube {
  Youtube._();

  static const _kFontFam = 'Youtube';
  static const _kFontPkg = null;

  static const IconData youtube = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
